# SPDX-FileCopyrightText: 20210 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22']

    name: node${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
