# SPDX-FileCopyrightText: 20210 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    name: node${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
